### ISSUE TITLE
No Documentation

### ISSUE THREAD

**Issue by ahmadSum1** [MARUSimulator/marus-example#2]
[API Documentation](https://github.com/MARUSimulator/marus-example/blob/main) leads to a 404 blank page.

**Comment by mandicLuka** [comment]
We had some problems with github action for documentation generation, this will be resolved soon

**Comment by rdesc** [comment]
Any updates on this? Thanks. Also to add, are there plans to make a more comprehensive documentation than what's already here https://marusimulator.github.io/ ?

**Comment by natkokrasevac** [comment]
Hi, [API documentation link](https://marusimulator.github.io/marus-api-documentation/api/index.html) in the README has been fixed. 

We are working on documenting the code better so there will be more detailed documentation in the near future.

As for usage documentation, we are also writing a new more in-depth pages to walk a new user through some common scenarios. This is in progress so be patient, thanks.

I will be closing this issue now. Feel free to open new issues as you encounter them.
Regards,
Natko
